In [1]:
#This cells needs to be ignored
#Here we are validating the create plugin functionality in Jhub
#All cells are Assumed to be script cells, unless explicitly marked as o9_ignore

In [1]:
from o9_common_utils.O9DataLake import O9DataLake, ResourceType, DataSource
query1 = "select (Version.[Version Name]*Product.[Product]*Time.FiscalWeek*SalesAccount.[Account]*Location.[Location]*{Measure.[DPSellOutUnitsActuals]}) limit 10;"
O9DataLake.register("sales_df",DataSource.LS, ResourceType.IBPL, query1)

2023-01-02 05:09:49,636 : srishtisingh_5502 :IbplClient: WebApi Request Url = [https://mygenieazure.o9solutions.com/api/ibplquery/5502/ExecuteCompactJsonQuery]
2023-01-02 05:09:49,639 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-02 05:09:50,313 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "POST /api/ibplquery/5502/ExecuteCompactJsonQuery HTTP/1.1" 200 None
2023-01-02 05:09:55,322 : srishtisingh_5502 :IbplClient: WebApi Request Url = [https://mygenieazure.o9solutions.com/api/ibplquery/5502/ExecuteCompactJsonQuery]
2023-01-02 05:09:55,326 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-02 05:09:56,076 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "POST /api/ibplquery/5502/ExecuteCompactJsonQuery HTTP/1.1" 200 None

,Version.[Version Name],Product.[Product],Time.[FiscalWeek],SalesAccount.[Account],Location.[Location],DPSellOutUnitsActuals
0,CurrentWorkingView,196426,W03-2016,ALL,ALL,1.0
1,CurrentWorkingView,196426,W05-2016,ALL,ALL,2.0
2,CurrentWorkingView,196426,W08-2016,ALL,ALL,1.0
3,CurrentWorkingView,196426,W13-2016,ALL,ALL,1.0
4,CurrentWorkingView,196426,W48-2016,ALL,ALL,1.0
5,CurrentWorkingView,196426,W42-2017,ALL,ALL,1.0
6,CurrentWorkingView,196426,W44-2017,ALL,ALL,1.0
7,CurrentWorkingView,208821,W03-2016,ALL,ALL,58.0
8,CurrentWorkingView,208821,W04-2016,ALL,ALL,45.0
9,CurrentWorkingView,208821,W05-2016,ALL,ALL,51.0

In [32]:
#getting input from dataLake

sales = O9DataLake.get('sales_df')


#User Script
import logging
logger = logging.getLogger('o9_logger')
logger.info(f'Records count in sales dataframe : {sales.shape}')
sales.head()

2023-01-02 09:57:46,530 : srishtisingh_5502 :IbplClient: WebApi Request Url = [https://mygenieazure.o9solutions.com/api/ibplquery/5502/ExecuteCompactJsonQuery]
2023-01-02 09:57:46,535 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-02 09:57:46,678 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "POST /api/ibplquery/5502/ExecuteCompactJsonQuery HTTP/1.1" 200 None
2023-01-02 09:57:51,687 : srishtisingh_5502 :IbplClient: WebApi Request Url = [https://mygenieazure.o9solutions.com/api/ibplquery/5502/ExecuteCompactJsonQuery]
2023-01-02 09:57:51,691 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-02 09:57:51,855 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "POST /api/ibplquery/5502/ExecuteCompactJsonQuery HTTP/1.1" 200 None
2023-01-02 09:57:56,872 : srishtisingh_5502 :Records count in sales dataframe : (10, 6)

,Version.[Version Name],Product.[Product],Time.[FiscalWeek],SalesAccount.[Account],Location.[Location],DPSellOutUnitsActuals
0,CurrentWorkingView,196426,W03-2016,ALL,ALL,500.0
1,CurrentWorkingView,196426,W05-2016,ALL,ALL,500.0
2,CurrentWorkingView,196426,W08-2016,ALL,ALL,500.0
3,CurrentWorkingView,196426,W13-2016,ALL,ALL,500.0
4,CurrentWorkingView,196426,W48-2016,ALL,ALL,500.0

In [31]:
#pushing output to the DataLake
sales["DPSellOutUnitsActuals"] = "500"
O9DataLake.put('out_df1',sales)

2023-01-02 09:57:33,154 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-02 09:57:33,238 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "GET /api/framework/sessions/session/authToken?authToken=11qx4vtyj1uj45ka2qptcabm HTTP/1.1" 200 None
2023-01-02 09:57:33,242 : srishtisingh_5502 :Uploading LOCAL file: /tmp/tmpa03qbtk_/Fact.out_df1.csv
2023-01-02 09:57:33,243 : srishtisingh_5502 :Is the file parquet: False
2023-01-02 09:57:33,245 : srishtisingh_5502 :Uploading /tmp/tmpa03qbtk_/Fact.out_df1.csv to Live Server cloud
2023-01-02 09:57:33,246 : srishtisingh_5502 :File size less than 256 MB
2023-01-02 09:57:33,247 : srishtisingh_5502 :Uploading to /fileUpload endpoint
2023-01-02 09:57:33,248 : srishtisingh_5502 :Uploading /tmp/tmpa03qbtk_/Fact.out_df1.csv to Live Server cloud
2023-01-02 09:57:33,252 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-02 09:57:35,481 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "POST /api/upload/fileUpload HTTP/1.1" 200 None
2023-01-02 09:57:35,486 : srishtisingh_5502 :Uploaded the file successfully
2023-01-02 09:57:35,489 : srishtisingh_5502 :Uploading cloud files at: "azure://IvrkBaeWLfmAdgA63s0q-YQjS9rnxeYLls4-lXy8ZCBb7W5Pos9YT7xPNvmWLQcstpUHxf3FCrS49exMY-SvVw2"
2023-01-02 09:57:35,490 : srishtisingh_5502 :IbplClient: WebApi Request Url = [https://mygenieazure.o9solutions.com/api/framework/sessions/session]
2023-01-02 09:57:35,494 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-02 09:57:35,593 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "GET /api/framework/sessions/session HTTP/1.1" 200 None
2023-01-02 09:57:35,598 : srishtisingh_5502 :logged into tenant pyplatformhivetest successfully
2023-01-02 09:57:35,599 : srishtisingh_5502 :IbplClient: WebApi Request Url = [https://mygenieazure.o9solutions.com/api/user]
2023-01-02 09:57:35,603 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-02 09:57:35,836 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "GET /api/user HTTP/1.1" 200 None
2023-01-02 09:57:35,847 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-02 09:57:35,936 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "GET /api/framework/sessions/session/authToken?authToken=11qx4vtyj1uj45ka2qptcabm HTTP/1.1" 200 None
2023-01-02 09:57:35,942 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-02 09:57:38,399 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "POST /api/ibplquery/5502/ExecuteQuery HTTP/1.1" 200 None
2023-01-02 09:57:38,402 : srishtisingh_5502 :200, OK
2023-01-02 09:57:38,403 : srishtisingh_5502 :Response json:
{"Result":"[{\"FileName\":\"Fact.out_df1.csv\",\"SheetName\":\"Fact.out_df1.csv\",\"TotalRows\":10,\"ProcessedRows\":10,\"Status\":\"Success\",\"Messages\":[\"Total Rows: [10]. Successfully Processed Rows: [10].\"],\"FileId\":\"azure://IvrkBaeWLfmAdgA63s0q-YQjS9rnxeYLls4-lXy8ZCBb7W5Pos9YT7xPNvmWLQcstpUHxf3FCrS49exMY-SvVw2\"}]","QueryGuid":"6de64ae4-bc23-4fc7-bc7c-41df9da58576","ImpactHeader":{"TenantId":5502,"TransactionId":"00000000-0000-0000-0000-000000000000","UpdatedMembers":null,"CreatedMembers":null,"DeletedMembers":null,"ModelImpact":{"DemandPlanning.Core.Inputs":{"DPBaseInputs":["DPSellOutUnitsActuals"]}}}}
2023-01-02 09:57:38,404 : srishtisingh_5502 :{'FileName': 'Fact.out_df1.csv', 'SheetName': 'Fact.out_df1.csv', 'TotalRows': 10, 'ProcessedRows': 10, 'Status': 'Success', 'Messages': ['Total Rows: [10]. Successfully Processed Rows: [10].'], 'FileId': 'azure://IvrkBaeWLfmAdgA63s0q-YQjS9rnxeYLls4-lXy8ZCBb7W5Pos9YT7xPNvmWLQcstpUHxf3FCrS49exMY-SvVw2'}