In [4]:
_sales = "select ([WalmartTime].[Day] * [Version].[Version Name].[CurrentWorkingView]  * [Department].[Department_ID] * [Store].[Store_ID] * {Measure.[Weekly Sales]}); "
_features = "select( [WalmartTime].[Day] * [Version].[Version Name].[CurrentWorkingView] * [Store].[Store_ID] * { Measure.[Temperature], Measure.[Fuel Price], Measure.[MarkDown1] , Measure.[MarkDown2], Measure.[MarkDown3], Measure.[MarkDown4] , Measure.[MarkDown5] , Measure.[CPI] , Measure.[Unemployment]});"
_stores = "select([Store].[Store_ID] *[Store].[Type] *[Store].[Size]);"


# Initialize the O9DataLake with the input parameters and dataframes
# Data can be accessed with O9DataLake.get(<Input Name>)
# Overwritten values will not be reflected in the O9DataLake after initialization

from o9_common_utils.O9DataLake import O9DataLake, ResourceType, DataSource,PluginSetting
sales = O9DataLake.register("sales",data_source = DataSource.LS, entity_type = ResourceType.IBPL, query = _sales,plugin_setting = PluginSetting.Inputs)
features = O9DataLake.register("features",data_source = DataSource.LS, entity_type = ResourceType.IBPL, query = _features,plugin_setting = PluginSetting.Inputs)
stores = O9DataLake.register("stores",data_source = DataSource.LS, entity_type = ResourceType.IBPL, query = _stores,plugin_setting = PluginSetting.Inputs)
O9DataLake.register("Version.[Version Name]", data_source = DataSource.LS, entity_type = ResourceType.IBPL,plugin_setting = PluginSetting.SliceDimension)

O9DataLake.register("PredictedSales",data_source = DataSource.LS,entity_type = ResourceType.IBPL,plugin_setting = PluginSetting.Outputs)
script_params = O9DataLake.register({}, data_source = DataSource.LS,plugin_setting = PluginSetting.ScriptParam)

In [5]:
O9DataLake.inputs

{'sales': {'name': 'sales',
  'resource_type': <ResourceType.IBPL: 'ibpl_query'>,
  'data_source': <DataSource.LS: 'liveserver'>,
  'query': 'select ([WalmartTime].[Day] * [Version].[Version Name].[CurrentWorkingView]  * [Department].[Department_ID] * [Store].[Store_ID] * {Measure.[Weekly Sales]}); ',
  'std_count_limit': '200000',
  'df':        WalmartTime.[Day] Version.[Version Name]  Department.[Department_ID]  \
  0             02-05-2010     CurrentWorkingView                           1
  1             02-05-2010     CurrentWorkingView                           1
  2             02-05-2010     CurrentWorkingView                           1
  3             02-05-2010     CurrentWorkingView                           1
  4             02-05-2010     CurrentWorkingView                           1
  ...                  ...                    ...                         ...
  421565        10-26-2012     CurrentWorkingView                          50
  421566        10-26-2012     CurrentWorkingView                          50
  421567        10-26-2012     CurrentWorkingView                          50
  421568        10-26-2012     CurrentWorkingView                          50
  421569        10-26-2012     CurrentWorkingView                          65

          Store.[Store_ID]  Weekly Sales
  0                      1      24924.50
  1                     10      40212.84
  2                     11      19611.13
  3                     12      17426.75
  4                     13      46761.90
  ...                  ...           ...
  421565                23       7723.00
  421566                24        595.00
  421567                25       2317.00
  421568                27       2540.50
  421569                34      41457.76

  [421570 rows x 5 columns]},
 'features': {'name': 'features',
  'resource_type': <ResourceType.IBPL: 'ibpl_query'>,
  'data_source': <DataSource.LS: 'liveserver'>,
  'query': 'select( [WalmartTime].[Day] * [Version].[Version Name].[CurrentWorkingView] * [Store].[Store_ID] * { Measure.[Temperature], Measure.[Fuel Price], Measure.[MarkDown1] , Measure.[MarkDown2], Measure.[MarkDown3], Measure.[MarkDown4] , Measure.[MarkDown5] , Measure.[CPI] , Measure.[Unemployment]});',
  'std_count_limit': '200000',
  'df':      WalmartTime.[Day] Version.[Version Name]  Store.[Store_ID]  Temperature  \
  0           02-05-2010     CurrentWorkingView                 1        42.31
  1           02-05-2010     CurrentWorkingView                10        57.65
  2           02-05-2010     CurrentWorkingView                11        84.50
  3           02-05-2010     CurrentWorkingView                12        64.05
  4           02-05-2010     CurrentWorkingView                13        82.27
  ...                ...                    ...               ...          ...
  8185        07-26-2013     CurrentWorkingView                 5        48.86
  8186        07-26-2013     CurrentWorkingView                 6        68.91
  8187        07-26-2013     CurrentWorkingView                 7        18.79
  8188        07-26-2013     CurrentWorkingView                 8        74.71
  8189        07-26-2013     CurrentWorkingView                 9        54.03

        Fuel Price  MarkDown1  MarkDown2  MarkDown3  MarkDown4  MarkDown5  \
  0          2.572        NaN        NaN        NaN        NaN        NaN
  1          3.963   11265.62       7.90      14.95     919.45    2473.83
  2          2.653        NaN        NaN        NaN        NaN        NaN
  3          4.121   11772.46        NaN      61.63    3885.06    4225.11
  4          2.797        NaN        NaN        NaN        NaN        NaN
  ...          ...        ...        ...        ...        ...        ...
  8185       3.261    3408.93    3666.32       1.71     137.88    1706.42
  8186       2.780        NaN        NaN        NaN        NaN        NaN
  8187       3.103   13100.37    3096.60       1.73    4854.70    6266.04
  8188       2.759        NaN        NaN        NaN        NaN        NaN
  8189       3.669    3923.20      96.52      17.36     990.11    2755.72

               CPI  Unemployment
  0     211.096358         8.106
  1     130.741379         7.545
  2     214.666074         7.343
  3     131.037548        11.627
  4     126.128355         7.951
  ...          ...           ...
  8185  220.476019         5.943
  8186  211.894272         7.092
  8187  196.919506         8.256
  8188  214.250032         6.290
  8189  224.804683         5.667

  [8190 rows x 12 columns]},
 'stores': {'name': 'stores',
  'resource_type': <ResourceType.IBPL: 'ibpl_query'>,
  'data_source': <DataSource.LS: 'liveserver'>,
  'query': 'select([Store].[Store_ID] *[Store].[Type] *[Store].[Size]);',
  'std_count_limit': '200000',
  'df':     Store.[Store_ID] Store.[Type]  Store.[Size]
  0                  1            A        151315
  1                 10            B        126512
  2                 11            A        207499
  3                 12            B        112238
  4                 13            A        219622
  5                 14            A        200898
  6                 15            B        123737
  7                 16            B         57197
  8                 17            B         93188
  9                 18            B        120653
  10                19            A        203819
  11                 2            A        202307
  12                20            A        203742
  13                21            B        140167
  14                22            B        119557
  15                23            B        114533
  16                24            A        203819
  17                25            B        128107
  18                26            A        152513
  19                27            A        204184
  20                28            A        206302
  21                29            B         93638
  22                 3            B         37392
  23                30            C         42988
  24                31            A        203750
  25                32            A        203007
  26                33            A         39690
  27                34            A        158114
  28                35            B        103681
  29                36            A         39910
  30                37            C         39910
  31                38            C         39690
  32                39            A        184109
  33                 4            A        205863
  34                40            A        155083
  35                41            A        196321
  36                42            C         39690
  37                43            C         41062
  38                44            C         39910
  39                45            B        118221
  40                 5            B         34875
  41                 6            A        202505
  42                 7            B         70713
  43                 8            A        155078
  44                 9            B        125833}}

In [6]:
# Import packages  
import os
import numpy as np  
import pandas as pd  
import logging   
from sklearn import preprocessing  
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeRegressor  
from sklearn.metrics import mean_absolute_error  
 
# Initializing logger 
logger = logging.getLogger('o9_logger')  
  
sales_df = sales[['WalmartTime.[Day]', 'Department.[Department_ID]','Store.[Store_ID]','Weekly Sales']]  
features_df = features[['Store.[Store_ID]','WalmartTime.[Day]', 'Temperature','Fuel Price','MarkDown1','MarkDown2',  
          'MarkDown3', 'MarkDown4','MarkDown5', 'CPI', 'Unemployment']]  
  
stores_df = stores[['Store.[Store_ID]', 'Store.[Type]', 'Store.[Size]']]  
  
dataset = sales_df.merge(stores_df, how='left').merge(features_df, how='left')  
  
# Input dataframe
input_df = dataset  
logger.error("LOGGING INPUT DATAFRAME")  
logger.info(input_df.head())  
  
input_df.fillna(0, inplace=True)  
input_df = pd.get_dummies(input_df, columns=["Store.[Type]"])  
input_df.drop("Store.[Type]_C", axis=1, inplace=True)  
input_df_scaled = input_df  
  
# Normalize the independent variables  
min_max_scaler = preprocessing.MinMaxScaler()  
input_df_scaled[['Store.[Size]', 'Temperature', 'Fuel Price', 'MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5', 'CPI', 'Unemployment']] = min_max_scaler.fit_transform(input_df_scaled[['Store.[Size]', 'Temperature', 'Fuel Price', 'MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5', 'CPI', 'Unemployment']])  
  
logging.info("Dataframe after cleanup")  
logging.info(input_df_scaled.head())  
  
X = input_df_scaled.loc[:, ['Store.[Size]', 'Temperature', 'Fuel Price', 'MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5', 'CPI',  
       'Unemployment', 'Store.[Type]_A', 'Store.[Type]_B']]  
y = input_df_scaled[['Weekly Sales']]  
  
DTReg = DecisionTreeRegressor(max_depth=5)  
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75,test_size=0.25, shuffle=False )  
DTReg.fit(X_train, y_train)   # training the model  
test_pred = DTReg.predict(X_test)  # making predictions  
mse = mean_absolute_error(y_test, test_pred)  
  
logging.warning("Mean absolute error: {}".format(mse))  
  
train_pred = DTReg.predict(X_train)  
all_predictions = np.hstack( (train_pred,test_pred) )  
  
PredictedSales= sales[['Version.[Version Name]', 'WalmartTime.[Day]', 'Department.[Department_ID]','Store.[Store_ID]']]  
PredictedSales["Predicted Sales"] = all_predictions  
  
logging.info("Finishing Plugin Execution")

2024-07-16 10:26:18,134 - o9_logger - ERROR  - LOGGING INPUT DATAFRAME
2024-07-16 10:26:18,135 - o9_logger - INFO  -   WalmartTime.[Day]  Department.[Department_ID]  Store.[Store_ID]  \
0        02-05-2010                           1                 1
1        02-05-2010                           1                10
2        02-05-2010                           1                11
3        02-05-2010                           1                12
4        02-05-2010                           1                13

   Weekly Sales Store.[Type]  Store.[Size]  Temperature  Fuel Price  \
0      24924.50            A        151315        42.31       2.572
1      40212.84            B        126512        57.65       3.963
2      19611.13            A        207499        84.50       2.653
3      17426.75            B        112238        64.05       4.121
4      46761.90            A        219622        82.27       2.797

   MarkDown1  MarkDown2  MarkDown3  MarkDown4  MarkDown5         CPI  \
0        NaN        NaN        NaN        NaN        NaN  211.096358
1   11265.62        7.9      14.95     919.45    2473.83  130.741379
2        NaN        NaN        NaN        NaN        NaN  214.666074
3   11772.46        NaN      61.63    3885.06    4225.11  131.037548
4        NaN        NaN        NaN        NaN        NaN  126.128355

   Unemployment
0         8.106
1         7.545
2         7.343
3        11.627
4         7.951

WARNING:root:Mean absolute error: 14369.55314565393