In [1]:
# This cell is NOT editable. Overwrite variables on your own discretion.
# Any changes other than the script code will NOT BE SAVED!
# All cells are assumed to be script code cells, unless explictly tagged as 'o9_ignore'

In [1]:
# Slice Dimension Attributes defined in the plugin. Please check all queries and replace <KEY HERE> with a valid name.
# For example: If slice is defined by Version.[Version Name] and Time.[Month]
# input_df = ibpl Select ([Version].[Version Name].[<KEY HERE>] * [Time].[Month].[<KEY HERE>] * [Item].[Item Number]) on row, ({Measure.[M1], Measure.[M2]}) on column limit 5000;
#                             update <KEY HERE> to valid names
# input_df = ibpl Select ([Version].[Version Name].[CurrentWorkingView] * [Time].[Month].[January] * [Item].[Item Number]) on row, ({Measure.[M1], Measure.[M2]}) on column limit 5000;

_sales_df = "select (Version.[Version Name]*Product.[Product].[196426]*Time.FiscalWeek*SalesAccount.[Account]*Location.[Location]*{Measure.[DPSellOutUnitsActuals],Measure.[Mean Pricing Save PCT],Measure.[Placement Count],Measure.[Promotion Count],Measure.[DPSellOutPrice]});"
_DPBaseInputs = "select (Version.[Version Name]*Product.[Product].[196426]*Time.FiscalWeek*SalesAccount.[Account]*Location.[Location]*{Measure.[DPSellOutUnitsActuals],Measure.[Mean Pricing Save PCT],Measure.[Placement Count],Measure.[Promotion Count],Measure.[DPSellOutPrice]});"


# Initialize the O9DataLake with the input parameters and dataframes
# Data can be accessed with O9DataLake.get(<Input Name>)
# Overwritten values will not be reflected in the O9DataLake after initialization

from o9_common_utils.O9DataLake import O9DataLake, ResourceType, DataSource
sales_df = O9DataLake.register("sales_df",DataSource.LS, ResourceType.IBPL, _sales_df)
DPBaseInputs = O9DataLake.register("DPBaseInputs",DataSource.LS, ResourceType.IBPL, _DPBaseInputs)

In [3]:
#getting input from dataLake
sales = O9DataLake.get('sales_df')
dpbaseinputs = O9DataLake.get('DPBaseInputs')
sales.head()

,Version.[Version Name],Product.[Product],Time.[FiscalWeek],SalesAccount.[Account],Location.[Location],DPSellOutUnitsActuals,Mean Pricing Save PCT,Placement Count,Promotion Count,DPSellOutPrice
0,S1,196426,W03-2016,ALL,ALL,1.0,NaN,NaN,NaN,6.0
1,CurrentWorkingView,196426,W03-2016,ALL,ALL,1.0,NaN,NaN,NaN,6.0
2,S1,196426,W05-2016,ALL,ALL,2.0,NaN,NaN,NaN,9.5
3,CurrentWorkingView,196426,W05-2016,ALL,ALL,2.0,NaN,NaN,NaN,9.5
4,S1,196426,W08-2016,ALL,ALL,1.0,NaN,NaN,NaN,6.0

In [4]:
#User Script
import logging
out_df1 = None
logger = logging.getLogger('o9_logger')
logger.info(f'Records count in sales dataframe : {sales.shape}')
logger.info(f'Records count in DPBaseInputs dataframe : {dpbaseinputs.shape}')

INFO : Records count in sales dataframe : (14, 10)
INFO : Records count in DPBaseInputs dataframe : (14, 10)

In [5]:
#pushing output to the DataLake
O9DataLake.put('out_df1',sales)