In [11]:
from o9_common_utils.O9DataLake import O9DataLake, ResourceType, DataSource
query1 = "select (Version.[Version Name]*Product.[Product].[196426]*Time.FiscalWeek*SalesAccount.[Account]*Location.[Location]*{Measure.[DPSellOutUnitsActuals],Measure.[Mean Pricing Save PCT],Measure.[Placement Count],Measure.[Promotion Count],Measure.[DPSellOutPrice]});"
query2 = "select (Version.[Version Name]*Product.[Product].[196426]*Time.FiscalWeek*SalesAccount.[Account]*Location.[Location]*{Measure.[DPSellOutUnitsActuals],Measure.[Mean Pricing Save PCT],Measure.[Placement Count],Measure.[Promotion Count],Measure.[DPSellOutPrice]});"
O9DataLake.register("sales_df",DataSource.LS, ResourceType.IBPL, query1) 
O9DataLake.register("DPBaseInputs",DataSource.LS, ResourceType.IBPL, query2)

2023-01-05 15:16:11,579 : srishtisingh_5502 :IbplClient: WebApi Request Url = [https://mygenieazure.o9solutions.com/api/ibplquery/5502/ExecuteCompactJsonQuery]
2023-01-05 15:16:11,583 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-05 15:16:11,691 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "POST /api/ibplquery/5502/ExecuteCompactJsonQuery HTTP/1.1" 200 None
2023-01-05 15:16:16,700 : srishtisingh_5502 :IbplClient: WebApi Request Url = [https://mygenieazure.o9solutions.com/api/ibplquery/5502/ExecuteCompactJsonQuery]
2023-01-05 15:16:16,703 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-05 15:16:16,788 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "POST /api/ibplquery/5502/ExecuteCompactJsonQuery HTTP/1.1" 200 None
2023-01-05 15:16:21,807 : srishtisingh_5502 :IbplClient: WebApi Request Url = [https://mygenieazure.o9solutions.com/api/ibplquery/5502/ExecuteCompactJsonQuery]
2023-01-05 15:16:21,811 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-05 15:16:21,907 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "POST /api/ibplquery/5502/ExecuteCompactJsonQuery HTTP/1.1" 200 None
2023-01-05 15:16:26,912 : srishtisingh_5502 :IbplClient: WebApi Request Url = [https://mygenieazure.o9solutions.com/api/ibplquery/5502/ExecuteCompactJsonQuery]
2023-01-05 15:16:26,916 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-05 15:16:27,015 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "POST /api/ibplquery/5502/ExecuteCompactJsonQuery HTTP/1.1" 200 None

,Version.[Version Name],Product.[Product],Time.[FiscalWeek],SalesAccount.[Account],Location.[Location],DPSellOutUnitsActuals,Mean Pricing Save PCT,Placement Count,Promotion Count,DPSellOutPrice
0,CurrentWorkingView,196426,W03-2016,ALL,ALL,11.0,NaN,NaN,NaN,10.0
1,CurrentWorkingView,196426,W05-2016,ALL,ALL,11.0,NaN,NaN,NaN,10.0
2,CurrentWorkingView,196426,W08-2016,ALL,ALL,11.0,NaN,NaN,NaN,10.0
3,CurrentWorkingView,196426,W13-2016,ALL,ALL,11.0,NaN,NaN,NaN,10.0
4,CurrentWorkingView,196426,W48-2016,ALL,ALL,11.0,NaN,NaN,NaN,10.0
5,CurrentWorkingView,196426,W42-2017,ALL,ALL,11.0,NaN,NaN,NaN,10.0
6,CurrentWorkingView,196426,W44-2017,ALL,ALL,11.0,NaN,NaN,NaN,10.0

In [12]:
sales = O9DataLake.get('sales_df')
sales

2023-01-05 15:16:32,057 : srishtisingh_5502 :IbplClient: WebApi Request Url = [https://mygenieazure.o9solutions.com/api/ibplquery/5502/ExecuteCompactJsonQuery]
2023-01-05 15:16:32,060 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-05 15:16:32,154 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "POST /api/ibplquery/5502/ExecuteCompactJsonQuery HTTP/1.1" 200 None
2023-01-05 15:16:37,164 : srishtisingh_5502 :IbplClient: WebApi Request Url = [https://mygenieazure.o9solutions.com/api/ibplquery/5502/ExecuteCompactJsonQuery]
2023-01-05 15:16:37,167 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-05 15:16:37,301 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "POST /api/ibplquery/5502/ExecuteCompactJsonQuery HTTP/1.1" 200 None

,Version.[Version Name],Product.[Product],Time.[FiscalWeek],SalesAccount.[Account],Location.[Location],DPSellOutUnitsActuals,Mean Pricing Save PCT,Placement Count,Promotion Count,DPSellOutPrice
0,CurrentWorkingView,196426,W03-2016,ALL,ALL,11.0,NaN,NaN,NaN,10.0
1,CurrentWorkingView,196426,W05-2016,ALL,ALL,11.0,NaN,NaN,NaN,10.0
2,CurrentWorkingView,196426,W08-2016,ALL,ALL,11.0,NaN,NaN,NaN,10.0
3,CurrentWorkingView,196426,W13-2016,ALL,ALL,11.0,NaN,NaN,NaN,10.0
4,CurrentWorkingView,196426,W48-2016,ALL,ALL,11.0,NaN,NaN,NaN,10.0
5,CurrentWorkingView,196426,W42-2017,ALL,ALL,11.0,NaN,NaN,NaN,10.0
6,CurrentWorkingView,196426,W44-2017,ALL,ALL,11.0,NaN,NaN,NaN,10.0

In [13]:
dpbaseinputs = O9DataLake.get('DPBaseInputs')

#User Script
import logging
out_df1 = None
logger = logging.getLogger('o9_logger')
#logger.info(f'Records count in sales dataframe : {sales.shape}')
#logger.info(f'Records count in DPBaseInputs dataframe : {dpbaseinputs.shape}')
logger.warning("Hello warning")
logger.error("Hello error")
logger.warning("Hello warning")

#pushing output to the DataLake
O9DataLake.put('out_df1',sales)

2023-01-05 15:16:42,350 : srishtisingh_5502 :IbplClient: WebApi Request Url = [https://mygenieazure.o9solutions.com/api/ibplquery/5502/ExecuteCompactJsonQuery]
2023-01-05 15:16:42,354 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-05 15:16:42,472 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "POST /api/ibplquery/5502/ExecuteCompactJsonQuery HTTP/1.1" 200 None
2023-01-05 15:16:47,480 : srishtisingh_5502 :IbplClient: WebApi Request Url = [https://mygenieazure.o9solutions.com/api/ibplquery/5502/ExecuteCompactJsonQuery]
2023-01-05 15:16:47,484 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-05 15:16:47,602 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "POST /api/ibplquery/5502/ExecuteCompactJsonQuery HTTP/1.1" 200 None
2023-01-05 15:16:52,620 : srishtisingh_5502 :Hello warning
2023-01-05 15:16:52,621 : srishtisingh_5502 :Hello error
2023-01-05 15:16:52,621 : srishtisingh_5502 :Hello warning
2023-01-05 15:16:52,627 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-05 15:16:52,759 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "GET /api/framework/sessions/session/authToken?authToken=11qx4vtyj1uj45ka2qptcabm HTTP/1.1" 200 None
2023-01-05 15:16:52,761 : srishtisingh_5502 :Uploading LOCAL file: /tmp/tmpjfxwk420/Fact.out_df1.csv
2023-01-05 15:16:52,763 : srishtisingh_5502 :Is the file parquet: False
2023-01-05 15:16:52,763 : srishtisingh_5502 :Uploading /tmp/tmpjfxwk420/Fact.out_df1.csv to Live Server cloud
2023-01-05 15:16:52,764 : srishtisingh_5502 :File size less than 256 MB
2023-01-05 15:16:52,765 : srishtisingh_5502 :Uploading to /fileUpload endpoint
2023-01-05 15:16:52,767 : srishtisingh_5502 :Uploading /tmp/tmpjfxwk420/Fact.out_df1.csv to Live Server cloud
2023-01-05 15:16:52,770 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-05 15:16:55,873 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "POST /api/upload/fileUpload HTTP/1.1" 200 None
2023-01-05 15:16:55,877 : srishtisingh_5502 :Uploaded the file successfully
2023-01-05 15:16:55,878 : srishtisingh_5502 :Uploading cloud files at: "azure://IvrkBaeWLfmAdgA63s0q-YQjS9rnxeYLls4-lXy8ZCBb7W5Pos9YT7xPNvmWLQcstpUHxf3FCrS49exMY-SvVw2"
2023-01-05 15:16:55,879 : srishtisingh_5502 :IbplClient: WebApi Request Url = [https://mygenieazure.o9solutions.com/api/framework/sessions/session]
2023-01-05 15:16:55,881 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-05 15:16:55,976 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "GET /api/framework/sessions/session HTTP/1.1" 200 None
2023-01-05 15:16:55,979 : srishtisingh_5502 :logged into tenant pyplatformhivetest successfully
2023-01-05 15:16:55,980 : srishtisingh_5502 :IbplClient: WebApi Request Url = [https://mygenieazure.o9solutions.com/api/user]
2023-01-05 15:16:55,982 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-05 15:16:56,247 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "GET /api/user HTTP/1.1" 200 None
2023-01-05 15:16:56,255 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-05 15:16:56,354 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "GET /api/framework/sessions/session/authToken?authToken=11qx4vtyj1uj45ka2qptcabm HTTP/1.1" 200 None
2023-01-05 15:16:56,359 : srishtisingh_5502 :Starting new HTTPS connection (1): mygenieazure.o9solutions.com:443
2023-01-05 15:16:58,968 : srishtisingh_5502 :https://mygenieazure.o9solutions.com:443 "POST /api/ibplquery/5502/ExecuteQuery HTTP/1.1" 200 None
2023-01-05 15:16:58,971 : srishtisingh_5502 :200, OK
2023-01-05 15:16:58,973 : srishtisingh_5502 :Response json:
{"Result":"[{\"FileName\":\"Fact.out_df1.csv\",\"SheetName\":\"Fact.out_df1.csv\",\"TotalRows\":7,\"ProcessedRows\":7,\"Status\":\"Success\",\"Messages\":[\"Total Rows: [7]. Successfully Processed Rows: [7].\"],\"FileId\":\"azure://IvrkBaeWLfmAdgA63s0q-YQjS9rnxeYLls4-lXy8ZCBb7W5Pos9YT7xPNvmWLQcstpUHxf3FCrS49exMY-SvVw2\"}]","QueryGuid":"1245d585-7096-4876-afdb-3c56420714a6","ImpactHeader":{"TenantId":5502,"TransactionId":"00000000-0000-0000-0000-000000000000","UpdatedMembers":null,"CreatedMembers":null,"DeletedMembers":null,"ModelImpact":{"DemandPlanning.Core.Inputs":{"DPBaseInputs":["DPSellOutUnitsActuals","Mean Pricing Save PCT","Placement Count","Promotion Count","DPSellOutPrice"]}}}}
2023-01-05 15:16:58,975 : srishtisingh_5502 :{'FileName': 'Fact.out_df1.csv', 'SheetName': 'Fact.out_df1.csv', 'TotalRows': 7, 'ProcessedRows': 7, 'Status': 'Success', 'Messages': ['Total Rows: [7]. Successfully Processed Rows: [7].'], 'FileId': 'azure://IvrkBaeWLfmAdgA63s0q-YQjS9rnxeYLls4-lXy8ZCBb7W5Pos9YT7xPNvmWLQcstpUHxf3FCrS49exMY-SvVw2'}