In [4]:
_input1 = "Select ([Version].[Version Name]* [Time].[FiscalWeek] * [Location].[Location] * [SalesAccount].[Account] * [Product].[Product] ) on row,  ({Measure.[Common Flyer Page Num], Measure.[Common Flyer Show IND], Measure.[Common Flyer Slot Num], Measure.[Common Flyer Slot Priority NM], Measure.[Common Flyer Slot Program NM], Measure.[DPSellInUnitsActuals], Measure.[DPSellInUnitsFcst], Measure.[DPSellInUnitsLCForecast], Measure.[DPSellInUnitsLYActuals], Measure.[DPSellOutAmountActuals], Measure.[DPSellOutPrice], Measure.[DPSellOutUnitsActuals], Measure.[DPSellOutUnitsFcst], Measure.[DPSellOutUnitsFcstPy], Measure.[DPSellOutUnitsFcstR], Measure.[DPSellOutUnitsLYActuals], Measure.[InputPicklist], Measure.[Mean Flyer Space Actual PCT], Measure.[Mean Pricing Promo Regular Natl Amt], Measure.[Mean Pricing Retail Regular Natl Amt], Measure.[Mean Pricing Save PCT], Measure.[OutputPicklist], Measure.[Placement Count], Measure.[Placement Flag], Measure.[Promotion Count], Measure.[Promotion Flag]}) on column LIMIT 20;"


# Initialize the O9DataLake with the input parameters and dataframes
# Data can be accessed with O9DataLake.get(<Input Name>)
# Overwritten values will not be reflected in the O9DataLake after initialization

from o9_common_utils.O9DataLake import O9DataLake, ResourceType, DataSource,PluginSetting
input1 = O9DataLake.register("input1",data_source = DataSource.LS, entity_type = ResourceType.IBPL, query = _input1,plugin_setting = PluginSetting.Inputs)
O9DataLake.register("Version.[Version Name]", data_source = DataSource.LS, entity_type = ResourceType.IBPL,plugin_setting = PluginSetting.SliceDimension)

O9DataLake.register("out_df1",data_source = DataSource.LS,entity_type = ResourceType.IBPL,plugin_setting = PluginSetting.Outputs)

In [5]:
input1

,Version.[Version Name],Time.[FiscalWeek],Location.[Location],SalesAccount.[Account],Product.[Product],Common Flyer Page Num,Common Flyer Show IND,Common Flyer Slot Num,Common Flyer Slot Priority NM,Common Flyer Slot Program NM,...,InputPicklist,Mean Flyer Space Actual PCT,Mean Pricing Promo Regular Natl Amt,Mean Pricing Retail Regular Natl Amt,Mean Pricing Save PCT,OutputPicklist,Placement Count,Placement Flag,Promotion Count,Promotion Flag
0,S1,W49-2015,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
1,CurrentWorkingView,W49-2015,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
2,S1,W50-2015,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
3,CurrentWorkingView,W50-2015,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
4,S1,W51-2015,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
5,CurrentWorkingView,W51-2015,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
6,S1,W52-2015,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
7,CurrentWorkingView,W52-2015,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
8,S1,W01-2016,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
9,CurrentWorkingView,W01-2016,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
10,S1,W02-2016,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
11,CurrentWorkingView,W02-2016,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
12,S1,W03-2016,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
13,CurrentWorkingView,W03-2016,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
14,S1,W04-2016,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
15,CurrentWorkingView,W04-2016,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
16,S1,W05-2016,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
17,CurrentWorkingView,W05-2016,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
18,S1,W06-2016,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN
19,CurrentWorkingView,W06-2016,ALL,ALL,85201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN